version: '3.1'

services:
  mongo:
    image: mongo:5.0.14
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_USER=${MONGO_INITDB_USER}
      - MONGO_INITDB_PWD=${MONGO_INITDB_PWD}
    volumes:
      - ./initdb.d/:/docker-entrypoint-initdb.d/
      - ./data:/data/db
    ports:
      - ${MONGO_PORT}:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${ME_PORT}:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true

networks:
  moe_lrs_network:
    external: true
